#ifndef PROJXGLOBAL_H__
#define PROJXGLOBAL_H__

typedef enum
{
    I_BASE1, I_BASE2, I_BASE3, I_BASE4, I_SPAWN1, I_SPAWN2, I_SPAWN3, I_SPAWN4, 
    I_NORMAL, I_ROAD, I_ROCK, I_FOREST1, I_FOREST2, I_WALL, I_STEELWALL, 
    I_WATER1, I_WATER2, I_WATER3, 
    
    I_TANK_UP1, I_TANK_UP2, I_TANK_UP3, I_TANK_DOWN1, I_TANK_DOWN2, 
    I_TANK_DOWN3, I_TANK_LEFT1, I_TANK_LEFT2, I_TANK_LEFT3, I_TANK_RIGHT1, 
    I_TANK_RIGHT2, I_TANK_RIGHT3,
    
    I_NORMAL_UP1, I_NORMAL_UP2, I_NORMAL_UP3, I_NORMAL_DOWN1, I_NORMAL_DOWN2, 
    I_NORMAL_DOWN3, I_NORMAL_LEFT1, I_NORMAL_LEFT2, I_NORMAL_LEFT3, 
    I_NORMAL_RIGHT1, I_NORMAL_RIGHT2, I_NORMAL_RIGHT3, 
    
    I_MISSILE,
    
    I_EXPLOSION
}
Global_image;

typedef enum
{
    SOUND_LEVELSTART, SOUND_VICTORY, SOUND_DEFEAT, SOUND_SCORE, SOUND_TANKFIRE1, 
    SOUND_TANKDEATH1, SOUND_PTDEATH, SOUND_BASEDEATH, SOUND_MISSILEEXPLOSION, 
    SOUND_WALLEXPLOSION
}
Global_sound;

typedef enum
{
    MUSIC_1, MUSIC_2, MUSIC_3, MUSIC_4, MUSIC_5, MUSIC_6, MUSIC_7, MUSIC_8, 
    MUSIC_9, MUSIC_10, MUSIC_11, MUSIC_12, MUSIC_13, MUSIC_14, MUSIC_15, 
    MUSIC_16, MUSIC_17
}
Global_music;

typedef enum
{
    TEXT_RUNNING, TEXT_PAUSED, TEXT_VICTORY, TEXT_DEFEATED, TEXT_SCORE, 
    TEXT_ENEMYREMAINING
}
Global_text;

typedef enum
{
    TILE_BASE, TILE_SPAWN, TILE_NORMAL, TILE_ROAD, TILE_ROCK, TILE_FOREST, 
    TILE_WALL, TILE_STEELWALL, TILE_WATER
}
Global_tile;

typedef enum
{
    TANK_LEFT, TANK_RIGHT, TANK_UP, TANK_DOWN
}
Global_tank_dir;

typedef enum
{
    PLAYERTANK, NORMALTANK, FASTTANK, HEAVYTANK, SUICIDALTANK, SPECIALTANK
}
Global_tank_type;

typedef enum
{
    EASY, NORMAL, INSANE, STEAMROLLING
}
Global_difficulty;

#endif
